name: NodeJS with Webpack

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  init:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
    - name: Build storybook
      run: npm run build:storybook
    - name: unit test
      run: npm run test:unit
    - name: e2e test
      run: npm run test:e2e
    - name: linting code
      run: npm run eslint
